const routes = {
  home: '/',
  minimal: '/minimal',
  swap: '/swap',
  liquidity: '/liquidity',
  liquidityPosition: '/liquidity-position',
  staking: '/empty',
  stakingTwo: '/staking-2',
  createNft: '/create-nft',
  nftDetails: '/nft-details',
  search: '/search',
  notification: '/notification',
  vote: '/empty',
  membership: '/membership',
  voteProposals: '/vote-proposals',
  createProposal: '/vote-proposals/create',
  charts: '/charts',
  proposals: '/proposals',
  treasury: '/treasury',
  about: '/about',
  settings: '/settings',
  portfolio: '/proposals?view=portfolio',
  history: '/proposals?view=history',
  classic: '/classic',
};

export default routes;
